use_frameworks!

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
source 'https://github.com/liuzhenhan/LZHPodSpec.git'


platform :ios, '10.0'

target 'LZHTools_Example' do
  pod 'LZHTools', :path => '../'

  target 'LZHTools_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
